use std::string::String;
use sha2::{Sha256, Digest};

pub fn generate_prediction(index: u128) -> (String, String) {
    // Special case for index 0 - GENESIS card
    if index == 0 {
        return (
            "EVERY JOURNEY BEGINS WITH A SINGLE STEP".to_string(),
            "千里之行，始于足下".to_string()
        );
    }
    
    let future = [
        ["Today", "今天"],
        ["Tomorrow", "明天"],
        ["This Morning", "今天早上"],
        ["This Afternoon", "今天下午"],
        ["This Evening", "今天晚上"],
        ["Tonight", "今晚"],
        ["Next Monday", "下周一"],
        ["Next Tuesday", "下周二"],
        ["Next Wednesday", "下周三"],
        ["Next Thursday", "下周四"],
        ["Next Friday", "下周五"],
        ["Next Saturday", "下周六"],
        ["Next Sunday", "下周日"],
        ["This Weekend", "本周末"],
        ["Next Week", "下周"],
        ["In Two Days", "两天后"],
        ["By Noon", "中午前"],
        ["At Night", "夜里"],
        ["Before Bed", "睡前"],
        ["After Breakfast", "早餐后"],
        ["During Lunch", "午餐时"],
        ["After Work", "下班后"],
        ["Before Dinner", "晚餐前"],
        ["At Sunrise", "日出时"],
        ["At Sunset", "日落时"],
        ["In the Morning", "早上"],
        ["In the Evening", "晚上"],
        ["This Night", "今夜"],
        ["Next Morning", "明早"],
        ["Next Evening", "明晚"],
        ["On Monday", "周一"],
        ["On Tuesday", "周二"],
        ["On Wednesday", "周三"],
        ["On Thursday", "周四"],
        ["On Friday", "周五"],
        ["On Saturday", "周六"],
        ["On Sunday", "周日"],
        ["This Week", "本周"],
        ["Next Weekend", "下个周末"],
        ["In Three Days", "三天后"],
        ["By Evening", "傍晚前"],
        ["After Lunch", "午饭后"],
        ["Before Noon", "中午前"],
        ["At Midnight", "午夜"],
        ["At Dawn", "黎明"],
        ["At Dusk", "黄昏"],
        ["Before Sunrise", "日出前"],
        ["After Sunset", "日落后"],
        ["During Breakfast", "早餐时"],
        ["During Dinner", "晚餐时"],
        ["After Midnight", "午夜后"],
        ["Before Midnight", "午夜前"],
        ["In Four Days", "四天后"],
        ["This Month", "本月"],
        ["Next Month", "下月"],
        ["By Tomorrow", "明天前"],
        ["By Tonight", "今晚前"],
        ["This Day", "今天"],
        ["Next Night", "明夜"]
    ];
    
    let subject = [
        ["You", "你"],
        ["Your Friend", "你的朋友"],
        ["Your Boss", "你的老板"],
        ["Your Colleague", "你的同事"],
        ["Your Neighbor", "你的邻居"],
        ["Your Partner", "你的伴侣"],
        ["Your Family", "你的家人"],
        ["Your Team", "你的团队"],
        ["Your Rival", "你的对手"],
        ["A Stranger", "陌生人"],
        ["Your Mentor", "你的导师"],
        ["Your Teacher", "你的老师"],
        ["Your Coworker", "你的同事"],
        ["Your Sibling", "你的兄弟姐妹"],
        ["Your Parent", "你的父母"],
        ["Your Child", "你的孩子"],
        ["Your Best Friend", "你最好的朋友"],
        ["Your Enemy", "你的敌人"],
        ["Your Classmate", "你的同学"],
        ["Your Manager", "你的经理"],
        ["Your Client", "你的客户"],
        ["Your Roommate", "你的室友"],
        ["Your Spouse", "你的配偶"],
        ["Your Crush", "你的暗恋对象"],
        ["Your Ex", "你的前任"],
        ["Your Doctor", "你的医生"],
        ["Your Accountant", "你的会计"],
        ["Your Coach", "你的教练"],
        ["Your Barber", "你的理发师"],
        ["Your Driver", "你的司机"],
        ["Your Waiter", "你的服务员"],
        ["Your Barista", "你的咖啡师"],
        ["Your Therapist", "你的治疗师"],
        ["Your Neighbor's Dog", "你邻居的狗"],
        ["Your Cat", "你的猫"],
        ["Your Dog", "你的狗"],
        ["Your Pet", "你的宠物"],
        ["Your Landlord", "你的房东"],
        ["Your Tenant", "你的租客"],
        ["Your Mailman", "你的邮递员"],
        ["Your Grocer", "你的杂货商"],
        ["Your Pharmacist", "你的药剂师"],
        ["Your Banker", "你的银行家"],
        ["Your Mechanic", "你的技工"],
        ["Your Plumber", "你的水管工"],
        ["Your Electrician", "你的电工"],
        ["Your Dentist", "你的牙医"],
        ["Your Hairdresser", "你的美发师"],
        ["Your Tailor", "你的裁缝"],
        ["Your Cleaner", "你的清洁工"],
        ["Your Gardener", "你的园丁"],
        ["Your Babysitter", "你的保姆"],
        ["Your Nanny", "你的保育员"],
        ["Your Tutor", "你的家教"],
        ["Your Advisor", "你的顾问"],
        ["Your Accountant", "你的会计"],
        ["Your Chef", "你的厨师"],
        ["Your Assistant", "你的助理"]
    ];
    
    let verb = [
        ["Will Triumph", "将成功"],
        ["Will Flop", "会失败"],
        ["Will Dominate", "将主宰"],
        ["Will Stumble", "会绊倒"],
        ["Will Discover", "会发现"],
        ["Will Reveal", "会揭示"],
        ["Will Cackle", "会大笑"],
        ["Will Weep", "会哭泣"],
        ["Will Hustle", "会奋斗"],
        ["Will Chill", "会放松"],
        ["Will Wander", "会徘徊"],
        ["Will Linger", "会逗留"],
        ["Will Clash", "会冲突"],
        ["Will Spark", "会激发"],
        ["Will Soothe", "会安慰"],
        ["Will Snub", "会冷落"],
        ["Will Rally", "会集结"],
        ["Will Grumble", "会抱怨"],
        ["Will Scheme", "会策划"],
        ["Will Ditch", "会抛弃"],
        ["Will Invent", "会发明"],
        ["Will Wreck", "会破坏"],
        ["Will Mend", "会修复"],
        ["Will Shatter", "会粉碎"],
        ["Will Snag", "会抓住"],
        ["Will Trade", "会交易"],
        ["Will Holler", "会呼喊"],
        ["Will Ping", "会联系"],
        ["Will Ghost", "会消失"],
        ["Will Recall", "会回忆"],
        ["Will Blank", "会空白"],
        ["Will Push", "会推动"],
        ["Will Bail", "会退出"],
        ["Will Launch", "会启动"],
        ["Will Wrap", "会结束"],
        ["Will Stall", "会拖延"],
        ["Will Sprint", "会冲刺"],
        ["Will Unwind", "会放松"],
        ["Will Freak", "会惊慌"],
        ["Will Sizzle", "会滋滋作响"],
        ["Will Feast", "会盛宴"],
        ["Will Crash", "会崩溃"],
        ["Will Groove", "会律动"],
        ["Will Croon", "会歌唱"],
        ["Will Brawl", "会争吵"],
        ["Will Grovel", "会卑躬屈膝"],
        ["Will Absolve", "会赦免"],
        ["Will Cram", "会死记"],
        ["Will Rage", "会愤怒"],
        ["Will Stash", "会藏匿"],
        ["Will Splurge", "会挥霍"],
        ["Will Rake", "会耙拉"],
        ["Will Misplace", "会遗失"],
        ["Will Uncover", "会发现"],
        ["Will Charm", "会吸引"],
        ["Will Fumble", "会失误"],
        ["Will Shine", "会闪耀"],
        ["Will Flirt", "会调情"],
        ["Will Roast", "会烤制"],
        ["Will Swagger", "会炫耀"]
    ];

    let mut hasher = Sha256::new();
    hasher.update(index.to_le_bytes());
    let hash = hasher.finalize();

    // Используем разные части хеша для определения типа предсказания
    let prediction_type = hash[24] % 2; // 0 или 1 для двух типов

    match prediction_type {
        0 => {
            // Персональные предсказания (существующие)
            let f_idx = (u64::from_le_bytes(hash[0..8].try_into().unwrap()) % future.len() as u64) as usize;
            let s_idx = (u64::from_le_bytes(hash[8..16].try_into().unwrap()) % subject.len() as u64) as usize;
            let v_idx = (u64::from_le_bytes(hash[16..24].try_into().unwrap()) % verb.len() as u64) as usize;

            let f = &future[f_idx];
            let s = &subject[s_idx];
            let v = &verb[v_idx];
            
            (
                format!("{} {} {}", f[0].to_uppercase(), s[0].to_uppercase(), v[0].to_uppercase()),
                format!("{} {} {}", f[1], s[1], v[1])
            )
        },
        _ => {
            // Общие пожелания (улучшенные) - убрал самые абстрактные фразы
            let general_beginnings = [
                ["Good fortune", "好运"],
                ["The stars", "星辰"],
                ["Luck smiles", "幸运微笑"],
                ["Your wish", "你的愿望"],
                ["The universe", "宇宙"],
                ["Your dreams", "你的梦想"],
                ["A surprise", "惊喜"],
                ["Change brings", "变化带来"],
                ["Your patience", "你的耐心"],
                ["A breakthrough", "突破"],
                ["The path", "道路"],
                ["Your efforts", "你的努力"],
                ["An angel", "天使"],
                ["Magic surrounds", "魔法围绕"],
                ["Your heart", "你的心"],
                ["A golden chance", "黄金机会"],
                ["The tides", "潮流"],
                ["Your strength", "你的力量"],
                ["A blessing", "祝福"],
                ["The road", "道路"],
                ["Your intuition", "你的直觉"],
                ["A pure wish", "纯净愿望"],
                ["Your energy", "你的能量"],
                ["A door opens", "门打开"],
                ["Your power", "你的力量"],
                ["Your courage", "你的勇气"],
                ["Perfect clarity", "完美清晰"],
                ["Your seeds", "你的种子"],
                ["Your true self", "真实的你"],
                ["Good luck", "好运"],
                ["Your inner light", "内在光芒"],
                ["Your gifts", "你的天赋"],
                ["Support surrounds", "支持围绕"],
                ["Wisdom finds", "智慧找到"],
                ["Your spark", "你的火花"],
                ["A bridge", "桥梁"],
                ["Harmony", "和谐"],
                ["Your resilience", "你的韧性"],
                ["A gentle touch", "温柔触碰"],
                ["Your love", "你的爱"],
                ["Your potential", "你的潜力"],
                ["A sacred time", "神圣时刻"],
                ["Peace", "和平"],
                ["Your journey", "你的旅程"],
                ["Celebration", "庆祝"],
                ["Truth reveals", "真相揭示"],
                ["Your spirit", "你的精神"],
                ["Connection", "连接"],
                ["Abundance flows", "丰盛流动"],
                ["Your voice", "你的声音"],
                ["Your story", "你的故事"],
                ["Healing begins", "治愈开始"],
                ["Your light", "你的光芒"]
            ];
            
            let general_middles = [
                ["awaits you", "等待你"],
                ["align for you", "为你排列"],
                ["upon you", "对你"],
                ["comes true", "成真"],
                ["helps you", "帮助你"],
                ["are near", "就在附近"],
                ["finds you", "找到你"],
                ["is rewarded", "得到回报"],
                ["is close", "即将到来"],
                ["is bright", "明亮"],
                ["bears fruit", "结果"],
                ["watches you", "注视你"],
                ["surrounds you", "围绕你"],
                ["is within reach", "触手可及"],
                ["appears", "出现"],
                ["turns for you", "为你转向"],
                ["shines through", "闪耀"],
                ["approaches", "接近"],
                ["leads to treasure", "通向宝藏"],
                ["guides you", "引导你"],
                ["manifests", "实现"],
                ["rewards you", "奖励你"],
                ["attracts miracles", "吸引奇迹"],
                ["unexpectedly", "意想不到"],
                ["transforms", "转变"],
                ["is celebrated", "被赞美"],
                ["arrives", "到来"],
                ["blooms", "绽放"],
                ["is recognized", "被认可"],
                ["washes over you", "冲刷你"],
                ["illuminates", "照亮"],
                ["is discovered", "被发现"],
                ["embraces you", "拥抱你"],
                ["finds you", "找到你"],
                ["ignites", "点燃"],
                ["appears", "出现"],
                ["is here", "在这里"],
                ["becomes your power", "成为你的力量"],
                ["reminds you", "提醒你"],
                ["returns multiplied", "成倍回报"],
                ["unfolds", "展开"],
                ["begins", "开始"],
                ["is yours", "是你的"],
                ["takes a turn", "转向"],
                ["awaits", "等待"],
                ["reveals itself", "揭示自己"],
                ["soars", "翱翔"],
                ["deepens", "加深"],
                ["flows freely", "自由流动"],
                ["is heard", "被听到"],
                ["reaches its peak", "达到顶峰"],
                ["is happening", "正在发生"],
                ["touches lives", "触动生命"]
            ];
            
            let general_endings = [
                ["with perfect timing", "在完美时机"],
                ["beyond dreams", "超越梦想"],
                ["in harmony", "和谐中"],
                ["unexpectedly", "意想不到"],
                ["when least expected", "最不期待时"],
                ["with joy", "带着喜悦"],
                ["miraculously", "奇迹般"],
                ["beyond measure", "超越衡量"],
                ["profoundly", "深刻地"],
                ["beautifully", "美丽地"],
                ["with fulfillment", "满足地"],
                ["with protection", "受保护"],
                ["infinitely", "无限地"],
                ["with satisfaction", "满足地"],
                ["with radiance", "光芒四射"],
                ["powerfully", "强大地"],
                ["brilliantly", "光辉地"],
                ["with blessings", "受祝福"],
                ["with treasures", "带着宝藏"],
                ["accurately", "准确地"],
                ["with pure intent", "纯净意图"],
                ["justly", "公正地"],
                ["magnetically", "磁性般"],
                ["in alignment", "完美排列"],
                ["transformatively", "转变地"],
                ["universally", "普遍地"],
                ["clearly", "清晰地"],
                ["beautifully", "美丽地"],
                ["genuinely", "真实地"],
                ["abundantly", "丰盛地"],
                ["warmly", "温暖地"],
                ["uniquely", "独特地"],
                ["unconditionally", "无条件地"],
                ["wisely", "智慧地"],
                ["creatively", "创意地"],
                ["where needed", "需要时"],
                ["in balance", "平衡中"],
                ["unbreakably", "不可打破"],
                ["gently", "温柔地"],
                ["exponentially", "指数级"],
                ["naturally", "自然地"],
                ["sacredly", "神圣地"],
                ["peacefully", "和平地"],
                ["beautifully", "美丽地"],
                ["honorably", "光荣地"],
                ["profoundly", "深刻地"],
                ["spiritually", "精神地"],
                ["deeply", "深深地"],
                ["limitlessly", "无限地"],
                ["authentically", "真实地"],
                ["perfectly", "完美地"],
                ["gently", "温柔地"],
                ["transformatively", "转变地"]
            ];
            
            let beg_idx = (u64::from_le_bytes(hash[0..8].try_into().unwrap()) % general_beginnings.len() as u64) as usize;
            let mid_idx = (u64::from_le_bytes(hash[8..16].try_into().unwrap()) % general_middles.len() as u64) as usize;
            let end_idx = (u64::from_le_bytes(hash[16..24].try_into().unwrap()) % general_endings.len() as u64) as usize;
            
            (
                format!("{} {} {}", general_beginnings[beg_idx][0].to_uppercase(), general_middles[mid_idx][0].to_uppercase(), general_endings[end_idx][0].to_uppercase()),
                format!("{} {} {}", general_beginnings[beg_idx][1], general_middles[mid_idx][1], general_endings[end_idx][1])
            )
        }
    }
}